/**
 * Validates commit subjects against the one format this repository accepts.
 *
 * A script rather than a workflow step, for two reasons: the rules are testable
 * (tests/unit/commit-messages.test.ts covers the cases below), and the same
 * check runs locally with `bun run commits:check` instead of only failing after
 * a push.
 *
 * The allowed types are the ones this repository actually uses — derived from
 * its own history, not copied from a generic list — plus the few that are
 * missing only because the occasion has not come up yet.
 *
 * Deliberately NOT enforced on the whole history: 28 existing commits predate
 * the convention ("Update .gitignore", "protected bug"). Rewriting published
 * history to satisfy a linter would be worse than the inconsistency, so the
 * check reads a range and CI passes it only the commits a pull request adds.
 */

/** Conventional Commit types, plus `security`, which this repo genuinely uses. */
export const TYPES = [
  'feat', // a capability a reader or another dev can observe
  'fix', // corrects behaviour that was wrong
  'perf', // same behaviour, measurably faster or lighter
  'refactor', // same behaviour, different shape
  'security', // hardening, dependency advisories, policy — not standard, but used here
  'docs', // prose: README, AGENTS.md, docs/, code comments
  'style', // formatting only, no behaviour
  'test', // tests and fixtures
  'build', // build pipeline, dependencies, lockfile
  'ci', // workflows and automation
  'chore', // housekeeping that fits nothing above
  'revert', // undoes a previous commit
] as const

export type CommitType = (typeof TYPES)[number]

/** Types that earn a CHANGELOG entry. The rest are curation, not history. */
export const CHANGELOG_TYPES: readonly CommitType[] = [
  'feat',
  'fix',
  'perf',
  'refactor',
  'security',
  'build',
]

const MAX_SUBJECT = 72
const MIN_DESCRIPTION = 10

/* `type(scope)!: description`
   - scope is optional, lowercase, may contain / and - for paths like (lab/csp)
   - `!` marks a breaking change
   - exactly one space after the colon */
const SUBJECT = /^([a-z]+)(?:\(([^()]*)\))?(!)?: (.*)$/

export interface Violation {
  subject: string
  problem: string
  hint: string
}

/** Merge and revert subjects are generated by git and GitHub; leave them be. */
const isGenerated = (subject: string): boolean =>
  /^(Merge|Revert) /.test(subject)

export const checkSubject = (subject: string): Violation | null => {
  const fail = (problem: string, hint: string): Violation => ({
    subject,
    problem,
    hint,
  })

  if (subject.trim() === '') return fail('empty subject', 'Write one.')
  if (isGenerated(subject)) return null

  const match = SUBJECT.exec(subject)
  if (!match) {
    // Say which half is wrong instead of restating the regex.
    if (!subject.includes(':')) {
      return fail(
        'no type prefix',
        `Start with a type and a colon, e.g. "feat(lab): add a subnet calculator". Allowed: ${TYPES.join(', ')}.`,
      )
    }
    return fail(
      'malformed prefix',
      'Expected `type(scope): description` with exactly one space after the colon, and a lowercase type.',
    )
  }

  const [, type, scope, breaking, description] = match

  if (!(TYPES as readonly string[]).includes(type)) {
    return fail(
      `unknown type "${type}"`,
      `Allowed: ${TYPES.join(', ')}. If none fits, the change is probably two changes.`,
    )
  }

  if (scope !== undefined) {
    if (scope.trim() === '') {
      return fail(
        'empty scope',
        'Either name the area — `feat(lab):` — or drop the parentheses entirely.',
      )
    }
    if (!/^[a-z0-9][a-z0-9/-]*$/.test(scope)) {
      return fail(
        `invalid scope "${scope}"`,
        'Lowercase letters, digits, `-` and `/` only, e.g. (lab), (notes), (lib/protection).',
      )
    }
  }

  const trimmed = description.trim()

  if (trimmed === '') {
    return fail(
      'no description',
      'The type says the category; the description has to say what changed.',
    )
  }
  if (description !== trimmed) {
    return fail(
      'padded description',
      'No leading or trailing whitespace after the colon.',
    )
  }
  if (trimmed.length < MIN_DESCRIPTION) {
    return fail(
      `description too short (${trimmed.length} chars)`,
      `At least ${MIN_DESCRIPTION}. "fix: bug" tells the next reader nothing.`,
    )
  }
  if (/^[A-Z][a-z]/.test(trimmed)) {
    return fail(
      'capitalised description',
      'Start lowercase — the subject reads as a sentence continuing from the type.',
    )
  }
  if (trimmed.endsWith('.')) {
    return fail('description ends in a period', 'A subject is not a sentence.')
  }
  if (subject.length > MAX_SUBJECT) {
    return fail(
      `subject too long (${subject.length} chars)`,
      `Keep it under ${MAX_SUBJECT} so it survives \`git log --oneline\`. Detail belongs in the body.`,
    )
  }
  if (breaking && !subject.includes('!:')) {
    return fail('misplaced breaking marker', 'Write `type(scope)!: …`.')
  }

  return null
}

export const checkSubjects = (subjects: readonly string[]): Violation[] =>
  subjects
    .map(checkSubject)
    .filter((violation): violation is Violation => violation !== null)

/* --- CLI ------------------------------------------------------------------ */

if (import.meta.main) {
  /* node:child_process rather than Bun's `$`: importing 'bun' here — even
     behind this guard — makes the module unresolvable for the test runner,
     which has to import the pure logic above. */
  const { execFileSync } = await import('node:child_process')

  /* `--title "<subject>"` checks one string instead of a range. A squash merge
     takes its subject from the pull request title, so an unchecked title would
     land a non-conforming commit on the branch regardless of the commits. */
  if (process.argv[2] === '--title') {
    const title = process.argv[3] ?? ''
    const violation = checkSubject(title)
    if (!violation) {
      console.log(`Title follows the convention: ${title}`)
      process.exit(0)
    }
    console.error(`  ✗ ${violation.subject}`)
    console.error(`    ${violation.problem}`)
    console.error(`    → ${violation.hint}`)
    process.exit(1)
  }

  const range = process.argv[2] ?? 'origin/main..HEAD'

  const raw = execFileSync(
    'git',
    ['log', range, '--no-merges', '--pretty=format:%s'],
    { encoding: 'utf8' },
  )
  const subjects = raw.split('\n').filter((line) => line.trim() !== '')

  if (subjects.length === 0) {
    console.log(`No commits to check in ${range}.`)
    process.exit(0)
  }

  const violations = checkSubjects(subjects)

  if (violations.length === 0) {
    console.log(
      `All ${subjects.length} commit subject(s) in ${range} follow the convention.`,
    )
    process.exit(0)
  }

  console.error(
    `${violations.length} of ${subjects.length} commit subject(s) do not follow the convention:\n`,
  )
  for (const { subject, problem, hint } of violations) {
    console.error(`  ✗ ${subject}`)
    console.error(`    ${problem}`)
    console.error(`    → ${hint}\n`)
  }
  console.error(
    'Amend with `git commit --amend` or, for several, `git rebase -i`.',
  )
  process.exit(1)
}
